debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    com.study.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: user
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver



  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  sql:
    init:
      mode: always
  data.rest:
      base-path: /api
      detection-strategy: annotated
  thymeleaf3.decoupled-logic: true

---

spring:
  config:
    activate:
      on-profile: heroku
  datasource:
    url: ${CLEARDB_DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always